FROM node:18-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json ./
RUN npm ci --only=production

COPY dist/src/main-cron.js ./dist/src/
COPY ./upload/Monitoring-every-day.csv ./data/

CMD ["node", "dist/src/main.js"]